### ISSUE TITLE
Build Oracle Table/View for apportionment and trip attributes

### ISSUE THREAD

**Issue by galuardi** [noaa-garfo/discaRd#9]
that has the functionality of the previous `cfders_vtr_apportionment`
merged with
`apsd.cams_trip_attribute `

**Comment by galuardi** [comment]
I think I've successfully rebuilt the trip attributes table. I created 

- STG_TRIP_ATTR
- CAMS_CATCH

as Views in MAPS

SQL is pushed to the MAPS repository under [trip_attributes](https://github.com/noaa-garfo/MAPS/tree/master/Code/trip_attributes)

Notes: 
- I dropped all MRI and active permit columns as they are not needed for discaRds.
- I made these as Views but they could/should be Tables or MViews. 

Next Step: 
- review the tables @danlinden @jmichaellanning 
- build the next step where Catch+OBS are merged

**Comment by djhocking** [comment]
Nice!

FYI:

1. in the CFDERS_VTR_IMPUTED table, AREA_SOURCE indicates where the area came from (AREA, CAREA, IMPUTE, PORT, WHSE). Not sure if you want to carry that through but wanted to make sure you were aware.
2. CFDERS_VTR_IMPUTED is way out of date and likely wrong in lots of places. It also might include PZero and rec trips but I'm not sure. I'm going to remake it today so it's just commercial trips and has all the updated data corrections. This is an advantage of your use of a view since it should just self update.

**Comment by djhocking** [comment]
I have updated the naming of the tables coming out of imputation for long term handling of all the data and making the partitions:

DLR_VTR = commercial landings from federal permits
DLR_VTR_ZERO = commercial landings from non-federal permits (Permit = '000000')
DLR_VTR_REC = recreational (PARTY/CHARTER) landings reported on VTR and/or sold to Dealers.

The use of DLR rather than CFDERS is to be internally consistent with Michael's data and column naming schemes as well.
